version: '3.8'

services:
  # 1. DATABASE UTAMA (MySQL untuk User, Product, Payment)
  cafe-db:
    image: mysql:8.0
    container_name: cafe-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - cafe_db_data:/var/lib/mysql
    networks:
      - cafe-network

  # 2. MESSAGE BROKER ASINKRON (RabbitMQ)
  cafe-rabbitmq:
    image: rabbitmq:3-management
    container_name: cafe-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cafe-network

  # 3. DATABASE INTERNAL HASURA (PostgreSQL)
  hasura-metadata-db:
    image: postgres:15
    container_name: hasura-metadata-db
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: hasura_metadata
    ports:
      - "5432:5432"
    networks:
      - cafe-network

  # 4. GRAPHQL ENGINE (Hasura Gateway)
  hasura:
    image: hasura/graphql-engine:v2.38.0
    container_name: cafe-hasura
    ports:
      - "8080:8080"
    depends_on:
      - hasura-metadata-db
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@hasura-metadata-db:5432/hasura_metadata
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
    networks:
      - cafe-network

  # 5. USER SERVICE (Vincent)
  user-service:
    build:
      context: ../userService
    container_name: user-service
    ports:
      - "8000:8000"
    depends_on:
      - cafe-db
    networks:
      - cafe-network

  # 6. PRODUCT SERVICE (Salwa)
  product-service:
    build:
      context: ../productService
    container_name: product-service
    ports:
      - "8001:8001"
    depends_on:
      - cafe-db
      - cafe-rabbitmq
    networks:
      - cafe-network

  # 7. ORDER SERVICE (Kamu)
  order-service:
    build:
      context: ../orderService
    container_name: order-service
    ports:
      - "8002:8002"
    depends_on:
      - hasura-metadata-db
      - cafe-rabbitmq
    networks:
      - cafe-network

  # 8. PAYMENT SERVICE (Niken)
  payment-service:
    build:
      context: ../paymentService
    container_name: payment-service
    ports:
      - "8003:8003"
    volumes:
      - ../paymentService:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: cafe-db
      DB_PORT: 3306
      DB_DATABASE: payment_db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - cafe-db
    networks:
      - cafe-network

  # 9. PAYMENT WORKER (Niken)
  payment-worker:
    build:
      context: ../paymentService
    container_name: payment-worker
    command: php artisan queue:work rabbitmq --queue=payment_queue
    volumes:
      - ../paymentService:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: cafe-db
      DB_PORT: 3306
      DB_DATABASE: payment_db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - cafe-rabbitmq
    networks:
      - cafe-network

networks:
  cafe-network:
    driver: bridge

volumes:
  cafe_db_data: